# Site settings
title: My notebook
email: 
description: >
  Trying to keep everything relevant to me here. It involves technologies, philosophy and books.
url: "http://gerep.github.io" # the base hostname & protocol for your site
twitter_username: danielgerep
github_username: gerep

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]